/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.assw.exerc.cio.weblinks.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class WeblinksApplication {

    public static void main(String[] args) {
        SpringApplication.run(WeblinksApplication.class, args);
    }
}
