server:
  port: 8080
spring:
  profiles: local
  applicatoion:
    name: assw-exerc-cio-weblinks-api
#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.assw.exerc.cio.weblinks.api: DEBUG
